server:
  port: 8766
spring:

  application:
    name: xiaofeizhe1
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}



