server:
  port: 8023
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accpt78
    username: root
    password: 123456
  application:
      name: tigongzhe
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}





